#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================
# SSH Hardening
# Debian / Ubuntu
# ============================================================

SSH_PORT="${SSH_PORT:-40022}"
TARGET_USER="${TARGET_USER:-root}"

AUTHORIZED_KEY="${AUTHORIZED_KEY:-ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFC93Qgfmw4/o6CIwSS+ILUYffhst07UZgJP8LimhUiy Generated By Termius}"

F2B_MAXRETRY="${F2B_MAXRETRY:-3}"
F2B_FINDTIME="${F2B_FINDTIME:-10m}"
F2B_BANTIME="${F2B_BANTIME:-10m}"

MANAGED_CONFIG="/etc/ssh/sshd_config.d/00-local-hardening.conf"

log() {
    printf '\033[1;32m[+] %s\033[0m\n' "$*"
}

warn() {
    printf '\033[1;33m[!] %s\033[0m\n' "$*"
}

die() {
    printf '\033[1;31m[-] %s\033[0m\n' "$*" >&2
    exit 1
}

# ------------------------------------------------------------
# 权限检查
# ------------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
    if command -v sudo >/dev/null 2>&1; then
        exec sudo -E bash "$0" "$@"
    else
        die "请使用 root 用户运行此脚本。"
    fi
fi

# ------------------------------------------------------------
# 参数检查
# ------------------------------------------------------------

if ! [[ "$SSH_PORT" =~ ^[0-9]+$ ]] ||
   (( SSH_PORT < 1 || SSH_PORT > 65535 )); then
    die "SSH_PORT 无效：$SSH_PORT"
fi

id "$TARGET_USER" >/dev/null 2>&1 ||
    die "用户不存在：$TARGET_USER"

TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
TARGET_GROUP="$(id -gn "$TARGET_USER")"

[[ -n "$TARGET_HOME" ]] ||
    die "无法获取 $TARGET_USER 的 Home 目录"

SSHD_BIN="$(command -v sshd || true)"

[[ -n "$SSHD_BIN" ]] ||
    die "未找到 sshd，请确认 openssh-server 已安装。"

# ------------------------------------------------------------
# 安装需要的软件
# ------------------------------------------------------------

if ! command -v ssh-keygen >/dev/null 2>&1 ||
   ! command -v fail2ban-client >/dev/null 2>&1; then

    log "安装所需软件..."

    export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y \
        openssh-client \
        fail2ban
fi

# ------------------------------------------------------------
# 验证公钥格式
# ------------------------------------------------------------

TMP_KEY="$(mktemp)"

printf '%s\n' "$AUTHORIZED_KEY" > "$TMP_KEY"

if ! ssh-keygen -lf "$TMP_KEY" >/dev/null 2>&1; then
    rm -f "$TMP_KEY"
    die "AUTHORIZED_KEY 不是有效的 SSH 公钥。"
fi

rm -f "$TMP_KEY"

log "SSH 公钥格式检查通过"

# ------------------------------------------------------------
# 创建备份
# ------------------------------------------------------------

BACKUP_DIR="/root/ssh-hardening-backup-$(date +%Y%m%d-%H%M%S)"

mkdir -p "$BACKUP_DIR"

cp -a /etc/ssh/sshd_config \
    "$BACKUP_DIR/sshd_config"

HAD_CONFIG_D=0

if [[ -d /etc/ssh/sshd_config.d ]]; then
    HAD_CONFIG_D=1
    cp -a /etc/ssh/sshd_config.d \
        "$BACKUP_DIR/sshd_config.d"
fi

AUTH_KEYS="$TARGET_HOME/.ssh/authorized_keys"

if [[ -f "$AUTH_KEYS" ]]; then
    cp -a "$AUTH_KEYS" \
        "$BACKUP_DIR/authorized_keys"
fi

log "配置已备份至：$BACKUP_DIR"

# ------------------------------------------------------------
# 配置 authorized_keys
# ------------------------------------------------------------

install -d \
    -m 700 \
    -o "$TARGET_USER" \
    -g "$TARGET_GROUP" \
    "$TARGET_HOME/.ssh"

touch "$AUTH_KEYS"

chown "$TARGET_USER:$TARGET_GROUP" "$AUTH_KEYS"
chmod 600 "$AUTH_KEYS"

# 不覆盖已有密钥，只在不存在时添加
if grep -qxF "$AUTHORIZED_KEY" "$AUTH_KEYS"; then
    log "SSH 公钥已经存在，跳过添加"
else
    printf '%s\n' "$AUTHORIZED_KEY" >> "$AUTH_KEYS"
    log "SSH 公钥已添加"
fi

# ------------------------------------------------------------
# 准备 sshd_config.d
# ------------------------------------------------------------

mkdir -p /etc/ssh/sshd_config.d

# 确保主配置包含 drop-in
if ! grep -Eq \
    '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf' \
    /etc/ssh/sshd_config; then

    TMP_CONFIG="$(mktemp)"

    {
        echo 'Include /etc/ssh/sshd_config.d/*.conf'
        cat /etc/ssh/sshd_config
    } > "$TMP_CONFIG"

    cat "$TMP_CONFIG" > /etc/ssh/sshd_config

    rm -f "$TMP_CONFIG"

    log "已启用 sshd_config.d 配置目录"
fi

# ------------------------------------------------------------
# 清理可能冲突的旧设置
# ------------------------------------------------------------

SSH_CONFIG_FILES=(
    "/etc/ssh/sshd_config"
)

while IFS= read -r -d '' file; do
    SSH_CONFIG_FILES+=("$file")
done < <(
    find /etc/ssh/sshd_config.d \
        -maxdepth 1 \
        -type f \
        -name '*.conf' \
        -print0
)

for file in "${SSH_CONFIG_FILES[@]}"; do

    [[ -f "$file" ]] || continue

    # 注释掉已有的相关配置，避免多个配置互相覆盖
    sed -i -E \
        's/^([[:space:]]*)(Port|PubkeyAuthentication|PasswordAuthentication|KbdInteractiveAuthentication|PermitEmptyPasswords)([[:space:]]+.*)$/# ssh-hardening-disabled: \1\2\3/' \
        "$file"

done

# ------------------------------------------------------------
# 写入统一 SSH 配置
# ------------------------------------------------------------

cat > "$MANAGED_CONFIG" <<EOF
# ============================================================
# Managed by ssh-hardening.sh
# ============================================================

Port ${SSH_PORT}

PubkeyAuthentication yes

PasswordAuthentication no

KbdInteractiveAuthentication no

PermitEmptyPasswords no
EOF

chmod 644 "$MANAGED_CONFIG"

log "SSH 安全配置已生成"

# ------------------------------------------------------------
# 验证 SSH 配置
# ------------------------------------------------------------

rollback_ssh() {

    warn "正在恢复原 SSH 配置..."

    cp -a \
        "$BACKUP_DIR/sshd_config" \
        /etc/ssh/sshd_config

    rm -rf /etc/ssh/sshd_config.d

    if [[ "$HAD_CONFIG_D" == "1" ]]; then
        cp -a \
            "$BACKUP_DIR/sshd_config.d" \
            /etc/ssh/sshd_config.d
    fi
}

if ! "$SSHD_BIN" -t; then
    rollback_ssh
    die "sshd 配置检查失败，已经自动恢复。"
fi

log "sshd -t 配置检查通过"

SSHD_EFFECTIVE="$("$SSHD_BIN" -T)"

get_sshd_value() {
    local key="$1"

    printf '%s\n' "$SSHD_EFFECTIVE" |
        awk -v key="$key" '$1 == key {print $2; exit}'
}

PUBKEY_VALUE="$(get_sshd_value pubkeyauthentication)"
PASSWORD_VALUE="$(get_sshd_value passwordauthentication)"
KBD_VALUE="$(get_sshd_value kbdinteractiveauthentication)"
EMPTY_VALUE="$(get_sshd_value permitemptypasswords)"

mapfile -t EFFECTIVE_PORTS < <(
    printf '%s\n' "$SSHD_EFFECTIVE" |
        awk '$1 == "port" {print $2}'
)

if [[ "${PUBKEY_VALUE}" != "yes" ]] ||
   [[ "${PASSWORD_VALUE}" != "no" ]] ||
   [[ "${KBD_VALUE}" != "no" ]] ||
   [[ "${EMPTY_VALUE}" != "no" ]]; then

    rollback_ssh
    die "sshd 实际认证配置与预期不一致，已经恢复原配置。"
fi

if [[ "${#EFFECTIVE_PORTS[@]}" -ne 1 ]] ||
   [[ "${EFFECTIVE_PORTS[0]}" != "$SSH_PORT" ]]; then

    rollback_ssh
    die "检测到 SSH Port 配置冲突，已经恢复原配置。"
fi

log "sshd 实际配置检查通过"

# ------------------------------------------------------------
# 防火墙兼容处理
# ------------------------------------------------------------

if command -v ufw >/dev/null 2>&1; then

    if ufw status 2>/dev/null |
       grep -q '^Status: active'; then

        log "检测到 UFW，开放 TCP ${SSH_PORT}"

        ufw allow "${SSH_PORT}/tcp"
    fi
fi

if systemctl is-active --quiet firewalld 2>/dev/null; then

    log "检测到 firewalld，开放 TCP ${SSH_PORT}"

    firewall-cmd \
        --permanent \
        --add-port="${SSH_PORT}/tcp"

    firewall-cmd --reload
fi

# ------------------------------------------------------------
# 处理 systemd ssh.socket
# ------------------------------------------------------------

SSH_SOCKET=""

for unit in ssh.socket sshd.socket; do

    if systemctl is-active --quiet "$unit" 2>/dev/null; then
        SSH_SOCKET="$unit"
        break
    fi

done

if [[ -n "$SSH_SOCKET" ]]; then

    warn "检测到 systemd socket activation：$SSH_SOCKET"

    SOCKET_DROPIN="/etc/systemd/system/${SSH_SOCKET}.d"

    mkdir -p "$SOCKET_DROPIN"

    cat > "$SOCKET_DROPIN/99-ssh-hardening-port.conf" <<EOF
[Socket]
ListenStream=
ListenStream=${SSH_PORT}
EOF

    systemctl daemon-reload
    systemctl restart "$SSH_SOCKET"

else

    # --------------------------------------------------------
    # 普通 ssh.service / sshd.service
    # --------------------------------------------------------

    if systemctl cat ssh.service >/dev/null 2>&1; then

        SSH_SERVICE="ssh"

    elif systemctl cat sshd.service >/dev/null 2>&1; then

        SSH_SERVICE="sshd"

    else

        rollback_ssh
        die "找不到 ssh.service 或 sshd.service"
    fi

    # reload 优先，不中断已有 SSH 会话
    systemctl reload "$SSH_SERVICE" 2>/dev/null ||
        systemctl restart "$SSH_SERVICE"

fi

sleep 1

# ------------------------------------------------------------
# 检查端口是否实际监听
# ------------------------------------------------------------

if ! ss -lntH |
    awk -v port=":${SSH_PORT}" \
        '$4 ~ port"$" {found=1} END {exit !found}'; then

    rollback_ssh

    if [[ -n "$SSH_SOCKET" ]]; then
        systemctl daemon-reload
        systemctl restart "$SSH_SOCKET" || true
    else
        systemctl restart "$SSH_SERVICE" || true
    fi

    die "TCP ${SSH_PORT} 没有监听，已尝试恢复旧 SSH 配置。"
fi

log "SSH 已监听 TCP ${SSH_PORT}"

# ------------------------------------------------------------
# Fail2ban
# ------------------------------------------------------------

mkdir -p /etc/fail2ban/jail.d

cat > /etc/fail2ban/jail.d/sshd.local <<EOF
[sshd]

enabled = true

port = ${SSH_PORT}

backend = systemd

maxretry = ${F2B_MAXRETRY}

findtime = ${F2B_FINDTIME}

bantime = ${F2B_BANTIME}
EOF

if ! fail2ban-server -t; then
    die "Fail2ban 配置检查失败，请检查 /etc/fail2ban/jail.d/sshd.local"
fi

systemctl enable fail2ban >/dev/null 2>&1 || true
systemctl restart fail2ban

for i in $(seq 1 30); do

    if fail2ban-client ping >/dev/null 2>&1; then
        break
    fi

    sleep 0.2
done

# ------------------------------------------------------------
# 最终状态
# ------------------------------------------------------------

echo
echo "============================================================"
echo " SSH Hardening 完成"
echo "============================================================"
echo
echo "用户：      ${TARGET_USER}"
echo "SSH Port：  ${SSH_PORT}"
echo "密码登录：  Disabled"
echo "交互认证：  Disabled"
echo "公钥登录：  Enabled"
echo
echo "Fail2ban："
echo "  MaxRetry: ${F2B_MAXRETRY}"
echo "  FindTime: ${F2B_FINDTIME}"
echo "  BanTime:  ${F2B_BANTIME}"
echo
echo "备份目录："
echo "  ${BACKUP_DIR}"
echo
echo "sshd 当前配置："

"$SSHD_BIN" -T |
    egrep \
    '^(port|pubkeyauthentication|passwordauthentication|kbdinteractiveauthentication|permitemptypasswords) '

echo
echo "Fail2ban 状态："

fail2ban-client ping
fail2ban-client status sshd

echo
echo "============================================================"
echo "重要：不要立即关闭当前 SSH 会话。"
echo
echo "请另外打开一个终端测试："
echo
echo "ssh -p ${SSH_PORT} ${TARGET_USER}@服务器IP"
echo
echo "确认新连接成功后，再关闭当前 SSH 会话。"
echo "============================================================"
