#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================
# SSH Hardening
# Debian / Ubuntu
#
# 功能：
#   1. 添加 SSH 公钥（不覆盖已有密钥）
#   2. SSH 修改为 40022 端口
#   3. 开启公钥认证
#   4. 禁用密码认证
#   5. 禁用 Keyboard-Interactive 认证
#   6. root 仅允许公钥登录
#   7. 自动处理 UFW / firewalld
#   8. 自动兼容 ssh.service / sshd.service / ssh.socket
#   9. 安装并配置 Fail2ban
#  10. SSH 配置验证与安全回滚
# ============================================================


# ============================================================
# 用户配置
# ============================================================

SSH_PORT="${SSH_PORT:-40022}"

TARGET_USER="${TARGET_USER:-root}"

AUTHORIZED_KEY="${AUTHORIZED_KEY:-ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFC93Qgfmw4/o6CIwSS+ILUYffhst07UZgJP8LimhUiy Generated By Termius}"

F2B_MAXRETRY="${F2B_MAXRETRY:-3}"
F2B_FINDTIME="${F2B_FINDTIME:-10m}"
F2B_BANTIME="${F2B_BANTIME:-10m}"


# ============================================================
# 脚本管理文件
# ============================================================

MANAGED_CONFIG="/etc/ssh/sshd_config.d/00-local-hardening.conf"

F2B_CONFIG="/etc/fail2ban/jail.d/sshd.local"

SOCKET_DROPIN_FILE=""

MANAGED_CONFIG_EXISTED=0
F2B_CONFIG_EXISTED=0
SOCKET_DROPIN_EXISTED=0

SSH_SOCKET=""
SSH_SERVICE=""


# ============================================================
# 输出函数
# ============================================================

log() {
    printf '\033[1;32m[+] %s\033[0m\n' "$*"
}

warn() {
    printf '\033[1;33m[!] %s\033[0m\n' "$*"
}

die() {
    printf '\033[1;31m[-] %s\033[0m\n' "$*" >&2
    exit 1
}


# ============================================================
# 权限检查
# ============================================================

if [[ $EUID -ne 0 ]]; then
    die "请使用 root 用户运行此脚本，例如：sudo bash ssh-hardening.sh"
fi


# ============================================================
# 参数检查
# ============================================================

if ! [[ "$SSH_PORT" =~ ^[0-9]+$ ]] ||
   (( SSH_PORT < 1 || SSH_PORT > 65535 )); then

    die "SSH_PORT 无效：$SSH_PORT"

fi


if ! id "$TARGET_USER" >/dev/null 2>&1; then
    die "用户不存在：$TARGET_USER"
fi


TARGET_HOME="$(
    getent passwd "$TARGET_USER" |
    cut -d: -f6
)"

TARGET_GROUP="$(
    id -gn "$TARGET_USER"
)"


[[ -n "$TARGET_HOME" ]] ||
    die "无法获取 ${TARGET_USER} 的 Home 目录"


# ============================================================
# 安装需要的软件
# ============================================================

NEED_PACKAGES=()


if ! command -v sshd >/dev/null 2>&1 &&
   [[ ! -x /usr/sbin/sshd ]]; then

    NEED_PACKAGES+=("openssh-server")

fi


if ! command -v ssh-keygen >/dev/null 2>&1; then

    NEED_PACKAGES+=("openssh-client")

fi


if ! command -v fail2ban-client >/dev/null 2>&1; then

    NEED_PACKAGES+=("fail2ban")

fi


if ! command -v ss >/dev/null 2>&1; then

    NEED_PACKAGES+=("iproute2")

fi


if (( ${#NEED_PACKAGES[@]} > 0 )); then

    log "安装所需软件：${NEED_PACKAGES[*]}"

    export DEBIAN_FRONTEND=noninteractive

    apt-get update

    apt-get install -y "${NEED_PACKAGES[@]}"

else

    log "所需软件已经安装"

fi


# ============================================================
# 获取 sshd 路径
# ============================================================

SSHD_BIN="$(
    command -v sshd 2>/dev/null || true
)"


if [[ -z "$SSHD_BIN" ]] &&
   [[ -x /usr/sbin/sshd ]]; then

    SSHD_BIN="/usr/sbin/sshd"

fi


[[ -n "$SSHD_BIN" ]] ||
    die "未找到 sshd"


# ============================================================
# 验证 SSH 公钥
# ============================================================

TMP_KEY="$(mktemp)"

printf '%s\n' "$AUTHORIZED_KEY" > "$TMP_KEY"


if ! ssh-keygen -lf "$TMP_KEY" >/dev/null 2>&1; then

    rm -f "$TMP_KEY"

    die "AUTHORIZED_KEY 不是有效的 SSH 公钥"

fi


rm -f "$TMP_KEY"


KEY_BLOB="$(
    printf '%s\n' "$AUTHORIZED_KEY" |
    awk '{print $2}'
)"


[[ -n "$KEY_BLOB" ]] ||
    die "无法解析 SSH 公钥"


log "SSH 公钥格式检查通过"


# ============================================================
# 创建备份
# ============================================================

BACKUP_DIR="/root/ssh-hardening-backup-$(date +%Y%m%d-%H%M%S)"

mkdir -p "$BACKUP_DIR"


# ------------------------------------------------------------
# 主配置备份
# 仅作为人工恢复用途
# 脚本不会主动修改 sshd_config
# ------------------------------------------------------------

if [[ -f /etc/ssh/sshd_config ]]; then

    cp -a \
        /etc/ssh/sshd_config \
        "$BACKUP_DIR/sshd_config"

fi


# ------------------------------------------------------------
# 整个 sshd_config.d 备份
# 仅作为人工恢复用途
# ------------------------------------------------------------

if [[ -d /etc/ssh/sshd_config.d ]]; then

    cp -a \
        /etc/ssh/sshd_config.d \
        "$BACKUP_DIR/sshd_config.d"

fi


# ------------------------------------------------------------
# 记录脚本自己的 SSH 配置
# ------------------------------------------------------------

if [[ -f "$MANAGED_CONFIG" ]]; then

    MANAGED_CONFIG_EXISTED=1

    cp -a \
        "$MANAGED_CONFIG" \
        "$BACKUP_DIR/00-local-hardening.conf"

fi


# ------------------------------------------------------------
# authorized_keys 备份
# ------------------------------------------------------------

AUTH_KEYS="${TARGET_HOME}/.ssh/authorized_keys"


if [[ -f "$AUTH_KEYS" ]]; then

    cp -a \
        "$AUTH_KEYS" \
        "$BACKUP_DIR/authorized_keys"

fi


# ------------------------------------------------------------
# Fail2ban 配置备份
# ------------------------------------------------------------

if [[ -f "$F2B_CONFIG" ]]; then

    F2B_CONFIG_EXISTED=1

    cp -a \
        "$F2B_CONFIG" \
        "$BACKUP_DIR/sshd.local"

fi


log "配置已备份至：$BACKUP_DIR"


# ============================================================
# SSH 回滚函数
# ============================================================

rollback_ssh() {

    warn "正在恢复脚本管理的 SSH 配置..."


    # --------------------------------------------------------
    # 恢复 SSH drop-in
    # --------------------------------------------------------

    if [[ "$MANAGED_CONFIG_EXISTED" == "1" ]]; then

        cp -a \
            "$BACKUP_DIR/00-local-hardening.conf" \
            "$MANAGED_CONFIG"

    else

        rm -f "$MANAGED_CONFIG"

    fi


    # --------------------------------------------------------
    # 恢复 systemd ssh.socket drop-in
    # --------------------------------------------------------

    if [[ -n "$SOCKET_DROPIN_FILE" ]]; then

        if [[ "$SOCKET_DROPIN_EXISTED" == "1" ]]; then

            cp -a \
                "$BACKUP_DIR/99-ssh-hardening-port.conf" \
                "$SOCKET_DROPIN_FILE"

        else

            rm -f "$SOCKET_DROPIN_FILE"

        fi

        systemctl daemon-reload || true

    fi


    # --------------------------------------------------------
    # 尝试重新加载原 SSH
    # --------------------------------------------------------

    if [[ -n "$SSH_SOCKET" ]]; then

        systemctl restart "$SSH_SOCKET" 2>/dev/null || true

    elif [[ -n "$SSH_SERVICE" ]]; then

        systemctl restart "$SSH_SERVICE" 2>/dev/null || true

    fi


    warn "SSH 配置回滚完成"

}


# ============================================================
# Fail2ban 回滚函数
# ============================================================

rollback_fail2ban() {

    warn "正在恢复 Fail2ban 配置..."


    if [[ "$F2B_CONFIG_EXISTED" == "1" ]]; then

        cp -a \
            "$BACKUP_DIR/sshd.local" \
            "$F2B_CONFIG"

    else

        rm -f "$F2B_CONFIG"

    fi


    systemctl restart fail2ban 2>/dev/null || true


    warn "Fail2ban 配置已恢复"

}


# ============================================================
# 配置 authorized_keys
# ============================================================

install -d \
    -m 700 \
    -o "$TARGET_USER" \
    -g "$TARGET_GROUP" \
    "$TARGET_HOME/.ssh"


touch "$AUTH_KEYS"


chown \
    "$TARGET_USER:$TARGET_GROUP" \
    "$AUTH_KEYS"


chmod 600 "$AUTH_KEYS"


# ------------------------------------------------------------
# 检查密钥主体是否已经存在
#
# 忽略 Comment 差异，例如：
#
# ssh-ed25519 AAAA... Termius
# ssh-ed25519 AAAA... MyPC
#
# 会被识别成同一把 Key
# ------------------------------------------------------------

if awk -v key="$KEY_BLOB" '

{
    for (i = 1; i <= NF; i++) {
        if ($i == key) {
            found = 1
        }
    }
}

END {
    exit !found
}

' "$AUTH_KEYS"; then

    log "SSH 公钥已经存在，跳过添加"

else

    printf '%s\n' "$AUTHORIZED_KEY" >> "$AUTH_KEYS"

    log "SSH 公钥已添加"

fi


# ============================================================
# 检查 sshd_config.d
# ============================================================

mkdir -p /etc/ssh/sshd_config.d


if ! grep -Eq \
    '^[[:space:]]*Include[[:space:]]+/etc/ssh/sshd_config\.d/\*\.conf' \
    /etc/ssh/sshd_config; then

    die "未检测到 Include /etc/ssh/sshd_config.d/*.conf，请先检查 /etc/ssh/sshd_config"

fi


log "sshd_config.d 已启用"


# ============================================================
# 检查现有 SSH 配置
#
# 这里只检查，不修改
# ============================================================

log "检查现有 SSH 配置..."


SSH_CONFIG_FILES=(
    "/etc/ssh/sshd_config"
)


while IFS= read -r -d '' file; do

    SSH_CONFIG_FILES+=("$file")

done < <(

    find /etc/ssh/sshd_config.d \
        -maxdepth 1 \
        -type f \
        -name '*.conf' \
        ! -path "$MANAGED_CONFIG" \
        -print0 \
        2>/dev/null

)


FOUND_EXISTING=0


for file in "${SSH_CONFIG_FILES[@]}"; do

    [[ -f "$file" ]] || continue


    MATCHES="$(
        grep -nEi \
            '^[[:space:]]*(Port|PubkeyAuthentication|PasswordAuthentication|KbdInteractiveAuthentication|PermitEmptyPasswords|PermitRootLogin)[[:space:]]+' \
            "$file" \
            2>/dev/null || true
    )"


    if [[ -n "$MATCHES" ]]; then

        FOUND_EXISTING=1

        warn "发现现有 SSH 设置：$file"

        printf '%s\n' "$MATCHES"

    fi

done


if [[ "$FOUND_EXISTING" == "1" ]]; then

    warn "以上配置不会被脚本修改，稍后通过 sshd -T 检查最终生效值"

else

    log "未发现需要关注的旧 SSH 设置"

fi


# ============================================================
# 写入脚本管理的 SSH 配置
# ============================================================

cat > "$MANAGED_CONFIG" <<EOF
# ============================================================
# Managed by ssh-hardening.sh
# ============================================================

Port ${SSH_PORT}

PubkeyAuthentication yes

PasswordAuthentication no

KbdInteractiveAuthentication no

PermitEmptyPasswords no
EOF


# ------------------------------------------------------------
# root 用户：
#
# 禁止 root 密码登录
# 允许 root 公钥登录
# ------------------------------------------------------------

if [[ "$TARGET_USER" == "root" ]]; then

    cat >> "$MANAGED_CONFIG" <<'EOF'

PermitRootLogin prohibit-password
EOF

fi


chmod 644 "$MANAGED_CONFIG"


log "SSH 安全配置已生成：$MANAGED_CONFIG"


# ============================================================
# SSH 配置语法检查
# ============================================================

if ! "$SSHD_BIN" -t; then

    rollback_ssh

    die "sshd 配置语法检查失败，已经自动恢复"

fi


log "sshd -t 配置检查通过"


# ============================================================
# 检查最终实际生效配置
# ============================================================

SSHD_EFFECTIVE="$(
    "$SSHD_BIN" -T
)"


get_sshd_value() {

    local key="$1"

    printf '%s\n' "$SSHD_EFFECTIVE" |
        awk -v key="$key" \
            '$1 == key {print $2; exit}'

}


PUBKEY_VALUE="$(
    get_sshd_value pubkeyauthentication
)"

PASSWORD_VALUE="$(
    get_sshd_value passwordauthentication
)"

KBD_VALUE="$(
    get_sshd_value kbdinteractiveauthentication
)"

EMPTY_VALUE="$(
    get_sshd_value permitemptypasswords
)"


# ------------------------------------------------------------
# 端口允许重复出现，但最终只能存在一个不同端口
#
# 例如：
# Port 40022
# Port 40022
#
# 不算冲突
# ------------------------------------------------------------

mapfile -t EFFECTIVE_PORTS < <(

    printf '%s\n' "$SSHD_EFFECTIVE" |
        awk '$1 == "port" {print $2}' |
        sort -nu

)


if [[ "$PUBKEY_VALUE" != "yes" ]] ||
   [[ "$PASSWORD_VALUE" != "no" ]] ||
   [[ "$KBD_VALUE" != "no" ]] ||
   [[ "$EMPTY_VALUE" != "no" ]]; then

    rollback_ssh

    die "sshd 实际认证配置与预期不一致，已经恢复原配置"

fi


if [[ "${#EFFECTIVE_PORTS[@]}" -ne 1 ]] ||
   [[ "${EFFECTIVE_PORTS[0]}" != "$SSH_PORT" ]]; then

    warn "检测到的 SSH 端口：${EFFECTIVE_PORTS[*]:-未知}"

    rollback_ssh

    die "检测到 SSH Port 配置冲突，已经恢复原配置"

fi


# ------------------------------------------------------------
# root 登录方式检查
# ------------------------------------------------------------

if [[ "$TARGET_USER" == "root" ]]; then

    ROOT_LOGIN_VALUE="$(
        get_sshd_value permitrootlogin
    )"


    if [[ "$ROOT_LOGIN_VALUE" != "prohibit-password" ]] &&
       [[ "$ROOT_LOGIN_VALUE" != "without-password" ]]; then

        warn "PermitRootLogin 当前值：$ROOT_LOGIN_VALUE"

        rollback_ssh

        die "root 公钥登录策略未正确生效，已经恢复原配置"

    fi

fi


log "sshd 实际配置检查通过"


# ============================================================
# 防火墙兼容
#
# 只处理：
#   UFW
#   firewalld
#
# nftables / iptables 自定义规则不会自动修改
# ============================================================

if command -v ufw >/dev/null 2>&1; then

    if ufw status 2>/dev/null |
       grep -q '^Status: active'; then

        log "检测到 UFW，开放 TCP ${SSH_PORT}"

        ufw allow "${SSH_PORT}/tcp"

    fi

fi


if systemctl is-active --quiet firewalld 2>/dev/null; then

    log "检测到 firewalld，开放 TCP ${SSH_PORT}"

    firewall-cmd \
        --permanent \
        --add-port="${SSH_PORT}/tcp"

    firewall-cmd --reload

fi


# ============================================================
# 检测 systemd ssh.socket
# ============================================================

for unit in ssh.socket sshd.socket; do

    if systemctl is-active --quiet "$unit" 2>/dev/null ||
       systemctl is-enabled --quiet "$unit" 2>/dev/null; then

        SSH_SOCKET="$unit"

        break

    fi

done


# ============================================================
# SSH Socket Activation
# ============================================================

if [[ -n "$SSH_SOCKET" ]]; then

    warn "检测到 systemd Socket Activation：$SSH_SOCKET"


    SOCKET_DROPIN_DIR="/etc/systemd/system/${SSH_SOCKET}.d"

    SOCKET_DROPIN_FILE="${SOCKET_DROPIN_DIR}/99-ssh-hardening-port.conf"


    mkdir -p "$SOCKET_DROPIN_DIR"


    # --------------------------------------------------------
    # 备份已有 socket 配置
    # --------------------------------------------------------

    if [[ -f "$SOCKET_DROPIN_FILE" ]]; then

        SOCKET_DROPIN_EXISTED=1

        cp -a \
            "$SOCKET_DROPIN_FILE" \
            "$BACKUP_DIR/99-ssh-hardening-port.conf"

    fi


    # --------------------------------------------------------
    # 修改 systemd socket 监听端口
    # --------------------------------------------------------

    cat > "$SOCKET_DROPIN_FILE" <<EOF
[Socket]
ListenStream=
ListenStream=${SSH_PORT}
EOF


    systemctl daemon-reload


    if ! systemctl restart "$SSH_SOCKET"; then

        rollback_ssh

        die "无法重新启动 ${SSH_SOCKET}"

    fi


else

    # ========================================================
    # 普通 ssh.service / sshd.service
    # ========================================================

    if systemctl cat ssh.service >/dev/null 2>&1; then

        SSH_SERVICE="ssh"

    elif systemctl cat sshd.service >/dev/null 2>&1; then

        SSH_SERVICE="sshd"

    else

        rollback_ssh

        die "找不到 ssh.service 或 sshd.service"

    fi


    log "使用 SSH 服务：${SSH_SERVICE}.service"


    # --------------------------------------------------------
    # 优先 reload
    #
    # reload 通常不会断开已有 SSH 会话
    # --------------------------------------------------------

    if ! systemctl reload "$SSH_SERVICE" 2>/dev/null; then

        warn "SSH reload 失败，尝试 restart"


        if ! systemctl restart "$SSH_SERVICE"; then

            rollback_ssh

            die "SSH 服务重新加载失败"

        fi

    fi

fi


sleep 1


# ============================================================
# 检查 40022 是否实际监听
# ============================================================

if ! ss -lntH |
    awk -v port=":${SSH_PORT}" '

$4 ~ port"$" {
    found = 1
}

END {
    exit !found
}

'; then

    warn "没有检测到 TCP ${SSH_PORT} 监听"

    rollback_ssh


    if [[ -n "$SSH_SOCKET" ]]; then

        systemctl daemon-reload || true
        systemctl restart "$SSH_SOCKET" 2>/dev/null || true

    elif [[ -n "$SSH_SERVICE" ]]; then

        systemctl restart "$SSH_SERVICE" 2>/dev/null || true

    fi


    die "TCP ${SSH_PORT} 没有监听，已经尝试恢复旧 SSH 配置"

fi


log "SSH 已监听 TCP ${SSH_PORT}"


# ============================================================
# Fail2ban
# ============================================================

mkdir -p /etc/fail2ban/jail.d


cat > "$F2B_CONFIG" <<EOF
[sshd]

enabled = true

port = ${SSH_PORT}

backend = systemd

maxretry = ${F2B_MAXRETRY}

findtime = ${F2B_FINDTIME}

bantime = ${F2B_BANTIME}
EOF


# ============================================================
# Fail2ban 配置检查
# ============================================================

if ! fail2ban-server -t; then

    rollback_fail2ban

    die "Fail2ban 配置检查失败，已经恢复旧配置"

fi


log "Fail2ban 配置检查通过"


# ============================================================
# 启动 Fail2ban
# ============================================================

systemctl enable fail2ban >/dev/null 2>&1 || true


if ! systemctl restart fail2ban; then

    rollback_fail2ban

    die "Fail2ban 启动失败"

fi


# ------------------------------------------------------------
# 等待 Fail2ban Server 初始化
# ------------------------------------------------------------

F2B_READY=0


for i in $(seq 1 30); do

    if fail2ban-client ping >/dev/null 2>&1; then

        F2B_READY=1

        break

    fi

    sleep 0.2

done


if [[ "$F2B_READY" != "1" ]]; then

    warn "Fail2ban 服务已经启动，但 Client 暂时无法连接"

else

    log "Fail2ban 已启动"

fi


# ============================================================
# 最终状态
# ============================================================

echo
echo "============================================================"
echo " SSH Hardening 完成"
echo "============================================================"

echo
echo "用户：      ${TARGET_USER}"
echo "SSH Port：  ${SSH_PORT}"

echo
echo "SSH 认证："
echo "  公钥登录：      Enabled"
echo "  密码登录：      Disabled"
echo "  Keyboard Auth： Disabled"
echo "  空密码：        Disabled"

if [[ "$TARGET_USER" == "root" ]]; then

    echo "  Root Login：    Public Key Only"

fi


echo
echo "Fail2ban："
echo "  MaxRetry： ${F2B_MAXRETRY}"
echo "  FindTime： ${F2B_FINDTIME}"
echo "  BanTime：  ${F2B_BANTIME}"


echo
echo "脚本管理 SSH 配置："
echo "  ${MANAGED_CONFIG}"


echo
echo "Fail2ban 配置："
echo "  ${F2B_CONFIG}"


echo
echo "备份目录："
echo "  ${BACKUP_DIR}"


echo
echo "------------------------------------------------------------"
echo "sshd 当前实际配置："
echo "------------------------------------------------------------"

"$SSHD_BIN" -T |
    egrep \
    '^(port|pubkeyauthentication|passwordauthentication|kbdinteractiveauthentication|permitemptypasswords|permitrootlogin) '


echo
echo "------------------------------------------------------------"
echo "SSH 监听状态："
echo "------------------------------------------------------------"

ss -lntp |
    grep -E ":${SSH_PORT}[[:space:]]" || true


echo
echo "------------------------------------------------------------"
echo "Fail2ban 状态："
echo "------------------------------------------------------------"

fail2ban-client ping 2>/dev/null || true

fail2ban-client status sshd 2>/dev/null || true


echo
echo "============================================================"
echo "重要：暂时不要关闭当前 SSH 会话。"
echo
echo "请另外打开一个终端测试："
echo
echo "ssh -p ${SSH_PORT} ${TARGET_USER}@服务器IP"
echo
echo "确认新连接可以正常使用公钥登录后，"
echo "再关闭当前 SSH 会话。"
echo "============================================================"
